name: Post Facebook event if scheduled for tomorrow

on:
  schedule:
    # Kjører daglig kl. 08:00 norsk tid (06:00 UTC)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Tillater manuell kjøring via GitHub UI

jobs:
  post-event:
    runs-on: ubuntu-latest

    steps:
      # Kloner dette repoet
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installerer ønsket versjon av Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installerer nødvendige Python-pakker
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      # Kjører Python-scriptet med secrets som miljøvariabler
      - name: Run event posting script
        env:
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
        run: |
          python scripts/post_metrix_weekly_to_facebook.py
